import { Inter } from "next/font/google";
import "./globals.css";
import { MainNavbar } from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Emvee Engineers Pvt. Ltd",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
    <MainNavbar />
      <body className={`${inter.className} flex flex-col`}>
        <div className="flex-grow">{children}</div>
      </body>
    </html>
  );
}
