import Footer from '../../components/Footer'
import { MainNavbar } from '../../components/Navbar'
import React from 'react'

export const metadata = {
    title: "Emvee Engineers Pvt. Ltd",
    description: "Generated by create next app",
    icons: {
        icon: '/icon.png',
    },
};

const RootLayout = ({ children }) => {
return (
    <div className="flex flex-col">
        <main className="flex-grow">
            {children}
        </main>
    </div>
)
}

export default RootLayout