import Footer from '@/components/Footer';
import { MainNavbar } from '@/components/Navbar';
import React from 'react'

export const metadata = {
    title: "Emvee Engineers Pvt. Ltd",
    description: "Generated by create next app",
    icons: {
        icon: '/icon.png',
    },
};

const RootLayout = ({ children }) => {
return (
    <main>
        <MainNavbar />
        {children}
        <Footer />
    </main>
)
}

export default RootLayout